---
abstract: 'ICalendar for the Ethiopic Calendar System.'
author:
  - 'Daniel Yacob <dyacob@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Date-Ethiopic
no_index:
  directory:
    - t
    - inc
requires:
  Convert::Number::Ethiopic: '0.15'
  Date::ICal: '0'
  perl: '5.006001'
version: '0.14'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
